### ISSUE TITLE
'dict object' has no attribute u'ansible_eth1'

### ISSUE THREAD

**Issue by jmvbxx** [ansible-collections/ansible-consul#10]
Good afternoon, Brian!

I installed your role from Ansible Galaxy and I'm trying to install `consul` on a standalone server.

Here's basic information:
* `ansible 2.2.0.0`
* Installing on Ubuntu 16.04 (not officially supported)

Full error:
```
TASK [brianshumate.consul : Bootstrap configuration] ***************************
fatal: [consul]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: {{ hostvars[inventory_hostname]['ansible_'+consul_iface]['ipv4']['address'] }}: 'dict object' has no attribute u'ansible_eth1'"}
```

The playbook:
```
  - hosts: "consul"
    gather_facts: true
    become: yes
    vars:
      consul_node_role: "bootstrap" 
    roles:
    - { role: brianshumate.consul, tags: ["consul"] }
```

ansible.cfg
```
[defaults]
host_key_checking = False
```

Thanks in advance!

**Comment by brianshumate** [comment]
Hey there, Jason!

Thanks for the report.

It looks like you're hitting that error because your server(s) have just one network interface and the role currently expects two, but I should be able to add something to make it work in either case.

Just to clarify one other point, are you also just starting up one instance of Consul? This is generally discouraged, so the role is designed for at least 3 servers so there would also need to be something added if for example you wanted to just start one server in `-dev` mode.

**Comment by jmvbxx** [comment]
Thanks for your reply! For prod I never run fewer than three consul server instances but in this test case I had only set one up.

It appears you're correct. Here is the setup of the AWS instance:

```
ubuntu@ip-xxx.xx.xx.xxx:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr 06:29:ac:5f:ad:cd  
          inet addr:xxx.xx.xx.xxx  Bcast:xxx.xx.xx.xxx  Mask:255.255.240.0
          inet6 addr: fe80::429:acff:fe5f:adcd/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:102739 errors:0 dropped:0 overruns:0 frame:0
          TX packets:55552 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:137727440 (137.7 MB)  TX bytes:4140894 (4.1 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:164 errors:0 dropped:0 overruns:0 frame:0
          TX packets:164 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:12104 (12.1 KB)  TX bytes:12104 (12.1 KB)
```

**Comment by brianshumate** [comment]
Okay, so this issue is not really about having only one interface as the role should work fine that way, but due to how the role works with Vagrant based VirtualBox instances, it expects the intra-cluster communications to occur on the secondary interface or _eth1_ by default.

This is not set in stone however, and you can actually specify your own name for the preferred cluster communication interface with the `consul_iface` variable.

Taking your playbook and making this modification should work as expected:

```
  - hosts: "consul"
    gather_facts: true
    become: yes
    vars:
      consul_node_role: "bootstrap" 
    roles:
    - { role: brianshumate.consul, consul_iface: "eth0", tags: ["consul"] }
```

Can you confirm that this works for you?
