### ISSUE TITLE
retry_join wasn't filled for client node

### ISSUE THREAD

**Issue by chemeugene** [ansible-collections/ansible-consul#133]
How to reproduce:

1. Create 4 node cluster

> [consul_instances]
consul1.consul consul_node_role=bootstrap
consul2.consul consul_node_role=server
consul3.consul consul_node_role=server
consul4.local consul_node_role=client 

2. Run ansible with role debug

Expect: 

client.json will contain retry_join param filled with 3 server node and there is no need to join client node to cluster manually.

Actual:
for server nodes all is ok
for client node there is "retry_join": [] option in client.json/config.json

**Comment by groggemans** [comment]
Not sure what's going on here. The config template doesn't make a difference for server or client nodes, so this should never happen. Do you also observe this behavior when running the role against all four of the nodes at the same time?

Are you using any custom variables?

**Comment by brianshumate** [comment]
I think the issue is that currently, [client configuration](https://github.com/brianshumate/ansible-consul/blob/master/templates/config.json.j2#L109-L111) does not also get the `retry_join` that [server configuration does](https://github.com/brianshumate/ansible-consul/blob/master/templates/config.json.j2#L94-L101) at all, so I am going to add `retry_join` to the client config block also to fix this.

**Comment by chemeugene** [comment]
I found my mistake. It depends on how my playbook looks like.
Problem was revealed on playbook like this:
```
---
- hosts: frontend
  roles:
    - brianshumate.consul
  vars:
    consul_iface: eth1

- hosts: es_master_nodes
  roles:
    - brianshumate.consul
  vars:
    consul_iface: eth1
    consul_node_role: server
    consul_bootstrap_expect: true
```

But if I write playbook so - all is ok:
```
---
- hosts: consul_instances
  roles:
    - brianshumate.consul
```
In that case group specific variables defined in **group_vars** dir

So ticket may be closed as it seems don't need any fix
