### ISSUE TITLE
Error when launching just clients

### ISSUE THREAD

**Issue by ChrisMcKee** [ansible-collections/ansible-consul#143]
I already have a cluster and was aiming to launch clients but I keep hitting a bootstrap error.

```
FAILED! => 
{"msg": "The conditional check '_consul_bootstrap_servers | length > 1' failed. 
The error was: error while evaluating conditional (_consul_bootstrap_servers | length > 1): 
{% set __consul_bootstrap_servers = [] %}
{% for server in _consul_lan_servers %}
 {% set _consul_node_role = hostvars[server]['consul_node_role'] | default('client', true) %}
  {% if _consul_node_role == 'bootstrap' %}
    {% if __consul_bootstrap_servers.append(server) %}
    {% endif %}
  {% endif %}
 {% endfor %}
{{ __consul_bootstrap_servers }}: {% set __consul_lan_servers = [] %}
{% for server in consul_servers %}
  {% set _consul_datacenter = hostvars[server]['consul_datacenter'] | default('dc1', true) %}
  {% if _consul_datacenter == consul_datacenter %}
    {% if __consul_lan_servers.append(server) %}{% endif %}{% endif %}{% endfor %}
  {{ __consul_lan_servers }}: {% set _consul_servers = [] %}
  {% for host in groups[consul_group_name] %}
    {% set _consul_node_role = hostvars[host]['consul_node_role'] | default('client', true) %}
    {% if ( _consul_node_role == 'server' or _consul_node_role == 'bootstrap') %}
    {% if _consul_servers.append(host) %}
  {% endif %}
  {% endif %}
{% endfor %}
{{ _consul_servers }}: 'dict object' has no attribute u'consul_instances'
The error appears to have been in '/path/ansible-consul/tasks/asserts.yml': line 68, column 3, but maybe elsewhere in the file depending on the exact syntax problem. 
The offending line appears to be: 
- name: Fail if more than one bootstrap server is defined  ^ here"}
```

Using the playbook vars

```
  vars:
    consul_version: "1.0.5"
    consul_datacenter: "dev"
    consul_node_name: "{{ inventory_hostname_short }}"
    consul_ui: false
    consul_node_role: "client"
    consul_bootstrap_expect: false
    consul_encrypt_enable: ""
    consul_install_upgrade: false
    consul_acl_enable: true
    consul_acl_master_token_display: false
    consul_acl_master_token: "xxxx"
    consul_join: ["10.1.42.210","10.1.42.220","10.1.42.230"]
```

I imagine its user-error, or the script is wrongly expecting to setup consul client at the same time as the servers, can't quite work out which as I stare at the main.yml.

Any assistance appreciated 😃
