### ISSUE TITLE
ERROR! no action detected in task

### ISSUE THREAD

**Issue by schmel** [ansible-collections/ansible-consul#158]
System ubuntu 16.04. 
ansible 2.0.0.2
My playbook:
```
---
- name: "Install Consul Cluster"
  hosts: "consul_instances"
  become: True
  any_errors_fatal: true
  roles:
    - { role: "brianshumate.consul", tags: "consul" }
```

```
ansible@jmmmon:/etc/ansible/playbooks$ ansible-playbook consul.yml
ERROR! no action detected in task

The error appears to have been in '/etc/ansible/roles/brianshumate.consul/tasks/main.yml': line 19, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Include checks/asserts
  ^ here
```
