### ISSUE TITLE
Installing unzip fails on Ubuntu/Xenial

### ISSUE THREAD

**Issue by jkevlin** [ansible-collections/ansible-consul#179]
On command:
`BOX_NAME=ubuntu/xenial64 CONSUL_IFACE=enp0s8 vagrant up`

Error:
```
TASK [brianshumate.consul : Install unzip package] *****************************
fatal: [consul1.consul -> localhost]: FAILED! => {"changed": false, "msg": "Could not detect which package manager to use. Try gathering facts or setting the \"use\" option."}
```

Suggested solution:
Add os family check.
```
- name: Install unzip package
  apt: pkg=unzip state=present
  run_once: true
  when:
    - consul_install_dependencies | bool
    - ansible_os_family == "Debian"
```
