### ISSUE TITLE
On centos7.4 error  when execute task `Update alpine package manager (apk)`

### ISSUE THREAD

**Issue by rinetd** [ansible-collections/ansible-consul#200]
1. `ansible-galaxy install brianshumate.consul`

```yml
---
- name: Install Consul cluster
  hosts: consul_instances
  any_errors_fatal: true
  become: yes
  become_user: root
  roles:
    - { role: brianshumate.consul }

```

TASK [brianshumate.consul : Update alpine package manager (apk)] *******************************************************************************************************************************************
 [WARNING]: Unable to find '/etc/alpine-release' in expected paths (use -vvvvv to see paths)

fatal: [l19]: FAILED! => {"msg": "The conditional check 'lookup('file','/etc/alpine-release')' failed. The error was: An unhandled exception occurred while running the lookup plugin 'file'. Error was a <c
lass 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /etc/alpine-release\n\nThe error appears to have been in '/root/.ansible/roles/brianshumate.consul/tasks/install.yml
': line 60, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Update alpine package manager (apk)\n  ^ here\n"}

NO MORE HOSTS LEFT *****************************************************************************************************************************************************************************************
        to retry, use: --limit @/root/ansible/consul/main.retry
