### ISSUE TITLE
Boolean values given in extra-vars have unexpected behaviour

### ISSUE THREAD

**Issue by eeroniemi** [ansible-collections/ansible-consul#265]
When I pass boolean values in commandline parameters, Jinja2 templates of this role treats False as True.

How to reproduce:

Setup Vagrant environment to work in `examples/` directory.

Modify `examples/site.yml` so that all bool values that are used on config file are False:

```
- name: Assemble Consul cluster
  hosts: consul_instances
  any_errors_fatal: true
  become: true
  become_user: root
  vars:
    consul_tls_enable: False
    consul_acl_enable: False
    consul_encrypt_enable: False
    consul_autopilot_enable: False
    consul_disable_keyring_file: False
    consul_log_level: "INFO" # playbook default is INFO, but Vagrantfile has DEBUG
  roles:
    - brianshumate.consul
```

Run `vagrant up`

After your cluster is up run:

```
ansible-playbook -i vagrant_hosts \
	-e "consul_encrypt_enable=False" -e "consul_tls_enable=False" \
	-e "consul_acl_enable=False" -e "consul_autopilot_enable=False" \
	-e "consul_disable_keyring_file=False" -e "consul_raw_key=ffffff" \
	site.yml --diff --check
```

What is expected to happen is that nothing in `/etc/consul/config.json` should change because all bool variables are set to False, on both initial playbook and as command line parameters. What actually happens:

```
--- before: /etc/consul/config.json
+++ after: /home/eero/.ansible/tmp/ansible-local-21952x3kuqpce/tmpcpl0lqe3
@@ -1,4 +1,11 @@
 {
+    "acl": {
+        "default_policy": "allow",
+        "down_policy": "extend-cache",
+        "enabled": true,
+        "token_ttl": "30s",
+        "tokens": {}
+    },
     "addresses": {
         "dns": "127.0.0.1",
         "grpc": "127.0.0.1",
@@ -9,15 +16,20 @@
     "advertise_addr_wan": "10.1.42.220",
     "bind_addr": "10.1.42.220",
     "bootstrap": false,
+    "ca_file": "/etc/consul/ssl/ca.crt",
+    "cert_file": "/etc/consul/ssl/server.crt",
     "client_addr": "127.0.0.1",
     "data_dir": "/var/consul",
     "datacenter": "dc1",
+    "disable_keyring_file": true,
     "disable_update_check": false,
     "domain": "consul",
     "enable_local_script_checks": false,
     "enable_script_checks": false,
     "enable_syslog": true,
-    "log_level": "DEBUG",
+    "encrypt": "ffffff",
+    "key_file": "/etc/consul/ssl/server.key",
+    "log_level": "INFO",
     "node_name": "consul2",
     "performance": {
         "leave_drain_time": "5s",
@@ -33,6 +45,7 @@
         "serf_wan": 8302,
         "server": 8300
     },
+    "primary_datacenter": "dc1",
     "raft_protocol": 3,
     "retry_interval": "30s",
     "retry_interval_wan": "30s",
@@ -45,5 +58,9 @@
     "retry_max_wan": 0,
     "server": true,
     "syslog_facility": "local0",
-    "ui": true
+    "ui": true,
+    "verify_incoming": false,
+    "verify_incoming_https": false,
+    "verify_outgoing": true,
+    "verify_server_hostname": false
 }
```

Reason for this behaviour is that while passing variable with value False in command line extra-vars they are treated as strings, and therefore "False" becomes True. This seems to be expected behaviour on Ansible / Jinja2, and therefore it's good practice to use `| bool` filter with boolean variables (source: https://github.com/ansible/ansible/issues/15636)

I have fix for this, will open PR.
