### ISSUE TITLE
install_remote.yml :: Cleanup broken

### ISSUE THREAD

**Issue by vmwiz** [ansible-collections/ansible-consul#270]
The `with_fileglob` from the Cleanup task of `tasks/install_remote.yml` is incorrect:

```
- name: Cleanup
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob: '{{ /tmp/consul }}'
  tags: installation
```
Or the braces must be removed (like it was before 3cdf0df9b3fdce25a6d0f5d784f49603a864b446)
Or a new variable must be set in the defaults and set accordingly.
