### ISSUE TITLE
consul_group_name must be included in groups.

### ISSUE THREAD

**Issue by wanfintara** [ansible-collections/ansible-consul#273]
playbook configuration

```
- name: play 2
  hosts: localhost
  become: yes
  roles:
    - unzip
    - pip
    - role: brianshumate.consul
      consul_user: consul
      consul_group: consul
      consul_group_name: consul
      consul_node_role: server
      consul_bootstrap_expect: true
      consul_bootstrap_expect_value: 1
      consul_bind_address: 100.100.100.10
```

I always get this error when running ansible-playbook command

![image](https://user-images.githubusercontent.com/23230734/56721510-3df4e080-676f-11e9-8c43-0129ea19e64d.png)

i already try this also but still same error i get
```
- name: play 2
  hosts: localhost
  become: yes
  roles:
    - unzip
    - pip
    - role: brianshumate.consul
      consul_user: consul
      consul_node_role: server
      consul_bootstrap_expect: true
      consul_bootstrap_expect_value: 1
      consul_bind_address: 100.100.100.10
```

what is wrong in my playbook configuration file or lack of what configuration?

**Comment by kevit** [comment]
Seems like hosts must be in consul_instances group

```
---
all:
  children:
    consul_instances:
      hosts:
        consulmaster
        consulslave1
        consulslave2
  hosts:
    consulmaster:
...
```

**Comment by a-beliaev-altatec** [comment]
@kevit 
```yml
---
#
# Playbook to install Consul (service discovery, key-value storage)
#

- hosts: "{{stage}}"
  roles:
    - consul-install
```

I get `consul_group_name must be included in groups.` error. What should my playbook look like?
