### ISSUE TITLE
user 'consul' with ID 1042 created

### ISSUE THREAD

**Issue by haraldkoch** [ansible-collections/ansible-consul#31]
The role is templated to use `{{ consul_user }}` everywhere, but one of the first things that `tasks/main.yml` does is to create a user with a hardcoded name (consul) and a hardcoded ID (1042). This smells like a bug to me. At the very least, the hardcoded name should probably be changed to `"{{ consul_user }}"`. I also submit that the user ID should not be hardcoded, and that the consul user should be a system account, as follows:

```
- name: Add Consul user
  user:
    name: "{{ consul_user }}"
    comment: "Consul user"
    group: "{{ consul_group }}"
    system: yes
```

What are your thoughts?
