### ISSUE TITLE
retry_join list is not populated

### ISSUE THREAD

**Issue by tommyalatalo** [ansible-collections/ansible-consul#355]
Trying to deploy consul with a cluster of vagrant VMs locally, I'm unable to get the retry_join list populated even though I have debugged the variable `_consul_lan_servers` and `consul_datacenter` for each node, which correctly prints the nodes and the datacenter respectively. I also set `consul_retry_join_skip_hosts` explicitly to false since it's used to populate `consul_lan_servers`.

The template code for retry_join is:
```
    "retry_join":
    {% if not consul_retry_join_skip_hosts %}
      {% for server in _consul_lan_servers %}
      {%   set _ = consul_join.append(hostvars[server]['consul_advertise_address'] | default(hostvars[server]['consul_bind_address']) | default(hostvars[server]['ansible_default_ipv4']['address']) | mandatory) %}
      {% endfor %}
    {% endif %}
    {{ consul_join | map('ipwrap') | list | to_json }},
```

I cant see what would be wrong other than if I'm misunderstanding `consul_retry_join_skip_hosts`

> If true, the config value for retry_join won't be populated by the default hosts servers. The value can be initialized using consul_join

what are the docs referring to as "**the default hosts servers**"?

My configuration is as below, hosts.yml:
```
all:
  vars:
    ansible_user: vagrant
    ansible_connection: ssh
    ansible_sudo_pass: vagrant

  children:
    nodes:
      hosts:
        node-1:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          consul_node_role: bootstrap
        node-2:
          ansible_host: 127.0.0.1
          ansible_port: 2200
          consul_node_role: server
        node-3:
          ansible_host: 127.0.0.1
          ansible_port: 2201
          consul_node_role: server
      vars:
        consul_datacenter: vagrant
        ansible_python_interpreter: /usr/bin/python3
    consul_instances:
      children:
        nodes:
```

```
- hosts: nodes
  become: true
  become_method: sudo

  roles:
    - brianshumate.consul

    # consul
    consul_version: 1.6.2
    consul_architecture: amd64
    consul_os: linux

    consul_bin_path: /opt/bin/
    consul_config_path: /etc/consul.d/
    consul_data_path: /opt/consul
    consul_log_path: /var/log/consul
    consul_log_rotate_bytes: 50000000 #50MB
    consul_log_rotate_max_files: 5
    consul_user: consul
    consul_group: consul
    consul_manage_group: true
    consul_retry_join_skip_hosts: false
    consul_iface: "{{ iface }}"
    consul_bind_address: "{{ hostvars[inventory_hostname]['ansible_'+iface]['ipv4']['address'] }}"
    consul_advertise_address: "{{ hostvars[inventory_hostname]['ansible_'+iface]['ipv4']['address'] }}"
    consul_addresses_http: 0.0.0.0
    consul_client_address: 169.254.1.1
    consul_encrypt_enable: true
    consul_ui: true
    consul_enable_script_checks: true
    consul_node_role:
    consul_autopilot_enable: true
```
The `consul_bind_address` and `consul_advertise_address` are using a variable "iface" which I set to "eth1" in order to bind and advertise the correct network interface when using Vagrant, which occupies eth0.

I'm using Ansible 2.9.1 and Ubuntu 18.04 on my computer as well as the vagrant VMs.
The resulting config.json from the above settings:

```
{
    "addresses": {
        "dns": "169.254.1.1",
        "grpc": "169.254.1.1",
        "http": "0.0.0.0",
        "https": "169.254.1.1"
    },
    "advertise_addr": "192.168.0.42",
    "advertise_addr_wan": "192.168.0.42",
    "bind_addr": "192.168.0.42",
    "client_addr": "169.254.1.1",
    "data_dir": "/opt/consul",
    "datacenter": "vagrant",
    "disable_update_check": false,
    "domain": "consul",
    "enable_local_script_checks": false,
    "enable_script_checks": true,
    "encrypt": "Ot30Hto4jkmF3ggo9VRc9gSQ9iIRozQvg/gvPEks6x0=",
    "log_file": "/var/log/consul/consul.log",
    "log_level": "INFO",
    "log_rotate_bytes": 50000000,
    "log_rotate_duration": "24h",
    "log_rotate_max_files": 5,
    "node_name": "node-3",
    "performance": {
        "leave_drain_time": "5s",
        "raft_multiplier": 1,
        "rpc_hold_timeout": "7s"
    },
    "ports": {
        "dns": 8600,
        "grpc": -1,
        "http": 8500,
        "https": -1,
        "serf_lan": 8301,
        "serf_wan": 8302,
        "server": 8300
    },
    "raft_protocol": 3,
    "retry_interval": "30s",
    "retry_join": [],
    "retry_max": 0,
    "server": true,
    "translate_wan_addrs": false,
    "ui": true
}
```
