### ISSUE TITLE
Nodes are not joining automatically

### ISSUE THREAD

**Issue by MartinAhrer** [ansible-collections/ansible-consul#363]
I'm setting up a consul cluster with 3 nodes. Each node has the following ansible variables set

```
consul_bootstrap_expect: true
consul_bootstrap_expect_value: 3
consul_iface: eth1
consul_node_role: server
```

I already had to explicitly set `consul_bootstrap_expect_value: 3` which is supposed to be calculated from the provisioned nodes?

Also the nodes don't join. The generated /etc/consul/config.json has `"retry_join": []`
The playbook is as follows:

```
- name: Assemble Consul cluster
  hosts: consul_nodes
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
      - role: brianshumate.consul
        vars:
            consul_group_name: "consul_nodes"

```
The inventory is:
```
all:
    hosts:
    children:
        consul_nodes:
            hosts:
                consul0:
                consul1:
                consul2:
```
Am I missing some variable to set?
