### ISSUE TITLE
Issues with install -> Get Consul package checksum file

### ISSUE THREAD

**Issue by jonhatalla** [ansible-collections/ansible-consul#45]
```
- name: Get Consul package checksum file
  become: no
  connection: local
  get_url:
    url: "{{ consul_checksum_file_url }}"
    dest: "{{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS"
  run_once: true
  tags: installation
  when: consul_checksum.stat.exists == False
```

I realize this is executing on my local machine, and i can use wget and curl to successfully download the file.  

If i run it as is - I get the error: 
`Failed to validate the SSL certificate for releases.hashicorp.com:443`

if i run with the verify_certs flag set to no, i get this error:
`Request failed: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>`

if i download the file manually and place it in the desired location, i get similar errors when i get to downloading the binary for consul.

Any thoughts on a solution/workaround?
