### ISSUE TITLE
/etc/consul/config.json not produced as valid json after upgrading from ansible 2.10 to ansible 2.12

### ISSUE THREAD

**Issue by MartinAhrer** [ansible-collections/ansible-consul#457]
After upgrading from ansible 2.10 to 2.12 a playbook using version v2.6.1 of the consul role is not producing a valid /etc/consul/config.json.
All double-quotes (") are suddenly escaped and rendered as \" resulting in a non-parseable json.

My setup was working with 
```
ansible 2.10.3
  config file = None
  configured module search path = ['/Users/martin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.10.3_1/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.0 (default, Dec  3 2020, 16:09:02) [Clang 12.0.0 (clang-1200.0.32.27)]
```

After updating ansible I started to experience the misfunction.

```
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/Users/martin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/5.1.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/martin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.1 (main, Dec  6 2021, 23:20:29) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

My playbook contains some variable values including double curly braces that are prefixed with `!unsafe` so the placeholders are ignored by ansible and passed though to the consul configuration.

```
# TODO for compatibility 169.254.1.1 bindings are kept. They have to be removed as migration is done.
- name: Assemble consul cluster
  become: true
  hosts: consul_nodes
  roles:
    - role: consul
      vars:
        consul_version: "1.11.1"
        consul_install_upgrade: true
        consul_group_name: "consul_nodes"
        consul_addresses:
          dns: !unsafe '169.254.1.1 127.0.0.1 {{  GetPrivateIP }} {{ GetInterfaceIP  \"docker0\" }}' 
          http: !unsafe '169.254.1.1 {{  GetPrivateIP }} {{ GetInterfaceIP  \"docker0\" }}' 
          https: !unsafe '127.0.0.1 {{  GetPrivateIP }}' 
          grpc: "127.0.0.1"
        consul_client_address: "169.254.1.1" 
        consul_node_role: server
        consul_bootstrap_expect_value: 3
        consul_bootstrap_expect: true
```

My initial playbook didn't use `!unsafe` and it broke the consul config the same way. After adding `!unsafe` the configuration was valid.
So I was wondering if the effect is related to that feature, or this happens by coincidence.
Are those unsafe values passed properly or am I using this the wrong way.
