### ISSUE TITLE
Key not read by servers that need it

### ISSUE THREAD

**Issue by groggemans** [ansible-collections/ansible-consul#46]
Hi Brian,

Thanks for your work on this role!

When adding a server after initial setup, the key is not correctly read by the server.

I think it's a wrong check;
https://github.com/brianshumate/ansible-consul/blob/master/tasks/main.yml#L125

```yaml
- name: Read key for servers that require it
  set_fact:
    consul_raw_key: "{{ lookup('file', '/tmp/consul_raw.key') }}"
  when: consul_raw_key is not defined and bootstrap_marker.stat.exists
```
Servers that require it don't have the `bootstrap_marker` file. So I think the check should be `... and not bootstrap_marker.stat.exists`.

Happy to provide a PR if you can confirm.
