### ISSUE TITLE
consul cluster forme failed

### ISSUE THREAD

**Issue by charnet1019** [ansible-collections/ansible-consul#487]
`ansible version`: 2.12.6  

`inventory`:  
```
[consul_instances]
consul1 consul_node_role=bootstrap
consul2 consul_node_role=server
consul3 consul_node_role=server
consul4 consul_node_role=client
```

`playbook`  
```
---
- hosts: consul_instances
  gather_facts: yes

  roles:
    - role: consul
      vars:
        consul_version: 1.12.2
        consul_datacenter: dc1
        consul_addresses_http: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        consul_acl_enable: true
        consul_connect_enabled: true
        consul_install_upgrade: true
        consul_data_path: "/data/consul/data"
  tags:
    - consul
```

**Error Info**  
```
TASK [consul : Generate ACL master token] **************************************************************************************************************************************************
task path: /home/ansible/roles/consul/tasks/acl.yml:36
skipping: [consul1] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [consul : debug %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% bootstrap_state] ***********************************************************************************************************
task path: /home/ansible/roles/consul/tasks/acl.yml:42
skipping: [consul1] => {}
ok: [consul2] => {
    "bootstrap_state": {
        "changed": false,
        "failed": false,
        "stat": {
            "exists": false
        }
    }
}
skipping: [consul4] => {}
ok: [consul3] => {
    "bootstrap_state": {
        "changed": false,
        "failed": false,
        "stat": {
            "exists": false
        }
    }
}

TASK [consul : debug %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% consul_acl_master_token_keygen] ********************************************************************************************
task path: /home/ansible/roles/consul/tasks/acl.yml:46
skipping: [consul1] => {}
skipping: [consul4] => {}
ok: [consul2] => {
    "consul_acl_master_token_keygen": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}
ok: [consul3] => {
    "consul_acl_master_token_keygen": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}

TASK [consul : Save ACL master token] ******************************************************************************************************************************************************
task path: /home/ansible/roles/consul/tasks/acl.yml:50
skipping: [consul1] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}
fatal: [consul2]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to be in '/home/ansible/roles/consul/tasks/acl.yml': line 50, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Save ACL master token\n      ^ here\n"
}
fatal: [consul3]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to be in '/home/ansible/roles/consul/tasks/acl.yml': line 50, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Save ACL master token\n      ^ here\n"
}
skipping: [consul4] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}
```

---
`Use the following configuration to create successfully with the same playbook.`
`inventory`
```
consul1 consul_node_role=server consul_bootstrap_expect=true
consul2 consul_node_role=server consul_bootstrap_expect=true
consul3 consul_node_role=server consul_bootstrap_expect=true
consul4 consul_node_role=client
```
