### ISSUE TITLE
'consul_node_role' is undefined

### ISSUE THREAD

**Issue by sysadmin1337** [ansible-collections/ansible-consul#8]
```
TASK [brianshumate.consul : Create cluster groupings] **************************
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'consul_node_role' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/brianshumate.consul/tasks/main.yml': line 24, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create cluster groupings\n  ^ here\n"}
```

Changed to consul_node_name?

**Comment by sysadmin1337** [comment]
Run with `ansible-playbook -i localhost main.yml`

main.yml

```
---
- hosts: all
  any_errors_fatal: true
  user: root
  become: true
  roles:
    - { role: brianshumate.consul }
```

localhost inventory file

```
[localhost]
127.0.0.1 ansible_connection=local
```
