### ISSUE TITLE
Deploy only consul clients

### ISSUE THREAD

**Issue by discointheair** [ansible-collections/ansible-consul#98]
Hi

Please correct me if I am wrong:
ATM the role is only usable when all consul servers and clients are part of the hostgroup “cluster_nodes/consul_instances (latest)”. Therefore I have to be a server admin also when I only want to deploy a client. 
-> I cannot use the role out of the box as a consul client admin.

My quick and dirty solution was:

Playbook:

```
- hosts: "consulclients.com"
  remote_user: centos
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  roles:
    - consul  
  vars:
    consul_node_role: "client"
    consul_acl_agent_token: "MyClientToken"
    consul_tls_enable: "true"
    consul_join_servers:
      - "1.2.3.4"
      - "1.2.3.5"
      - "1.2.3.6"
    ...
```

config.json.j2:
```

    {## LAN Join ##}
    "start_join": [
			{% for server in consul_join_servers %}
					"{{ server }}",
			{% endfor %}
        {% for server in _consul_lan_servers %}
            "{{ hostvars[server]['consul_bind_address'] | ipwrap }}",
        {% endfor %} ],
```

Is it possible to add a “clients only mode” in one of the next releases?

**Comment by groggemans** [comment]
You could always add some dummy hosts to fix this problem.

I'll have a look at supporting this use-case in the future.
@brianshumate you can assign this issue to me

**Comment by discointheair** [comment]
Thank you. @groggemans 
Current solution:
```
    {## LAN Join ##}
    "retry_join": [
			{% if consul_join_servers is defined %}
			{% for server in consul_join_servers %}
					"{{ server }}",
			{% endfor %}
			{% endif %}
        {% for server in _consul_lan_servers %}
            "{{ hostvars[server]['consul_bind_address'] | ipwrap }}",
        {% endfor %} ],
```

I also changed start_join to retry_join, because i had problems with leader election.

**Comment by mechastorm** [comment]
FYI I am also trying to get the same functionality. I want to deploy just the consul agents in client mode but I keep getting depedencies errors on the need for the `consul_raw_key` which seems to be only need for the `gossip encryption key for servers that require it, so I don't see why clients would need it.

**Comment by mechastorm** [comment]
Actually my mistake, `consul_raw_key` is needed by all agents - the `server` put me off the track. The one issue I am now debugging is the config template var `hostvars[server]['consul_bind_address']` is missing.

**Comment by brianshumate** [comment]
The project has always been more about forming clusters of Consul servers and has not had much thought or work at all into deploying client only instances, but it is certainly a valid use case and would be nice to have so I hope it can be hashed out here and a PR done for the feature.

Let me know how I can help.

Thanks!

**Comment by discointheair** [comment]
Hi. I am in holidays the next week's. I changed the role for me  but it was not really compatible. Like Brian said the role is usefully to deploy servers and I will not try to include the client solution here. I think I will write a native bash and docker script for the client users. So they can use it within their deployment scripts.

**Comment by vincent-legoll** [comment]
@brianshumate, @groggemans : I'm willing to help make this happen.
I can test, or even start to work on implementing it, given some directions, maybe a task list.

**Comment by groggemans** [comment]
Currently running tests for a PR adding this feature and fixing #102

**Comment by groggemans** [comment]
Feature added in #116

**Comment by discointheair** [comment]
Hi @groggemans 

I use the feature now and am able to deploy clients only. Thank you.
There is one issue that you still need a (dummy) “consul_instances” hostgroup with consul_node_role: “server” entries, so that the role can complete without errors. 

```
- name: "Create consul server tenant group"
  add_host:
    name: "{{ item }}"
    groups: "consul_instances"
    consul_node_role: "server"
  with_items:
    - “foo”
```

For the rejoin from the client to servers I am than using only the new “consul_join” list and it works.
Thank you again for implementing it.
